### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by UriHerrera** [plasma-extensions/plasma-widget-quick-controls#1]
![](http://i.imgur.com/6e9oS5y.png)

What it is: The sidebar panel is an standalone application that provides users instant access to settings and controls. Controls for the connectivity, ergonomics and usability.

Features: Toggles for bluetooth, wifi, night mode (switch to dark theme), airplane mode, brightness slider (works only on laptops, notebooks, ultrabooks, etc.), media player, weather, application suggestions (taken from Discover) and session controls.
# 

Background: The idea is derived from 3 sources: Solus (Budgie), Deepin (Settings) and macOS Notification Center.

From a UX perspective how this kind of application works on the mentioned systems is because none of them have a system tray in the same manner as Plasma does (they weren't designed that way). Plasma's system tray is made up of separate applets; it has a legacy styled system tray (other examples are XFCE, LXDE, LXQt, Unity and of course Windows). For instance, in Budgie clicking the wifi icon (or ethernet) opens the full panel instead of just the applet (like in Plasma) because it's idea is to offer a centralized settings/notifications location. Deepin does it even more differently, it's side panel is not for quick access but to provide a centralized general settings area though it doesn't provide notifications.

The concept to centralize the settings adds an alternative method for users to conveniently access these settings and controls. The application would need to provide a plasmoid to access it from a panel in place of the default system tray (like how the Menu plasmoid launches the Application Dashboard which isn't a plasmoid itself but a standalone application but also provides access to the other two menus: Kicker and Kickoff. In other words, that it is selectable as an _Alternative_ in the right-click context menu).
# 

If you notice too some of the icons are different since they're not from Breeze. I used Nitrux icons.

This just the view of the _Controls_. I'll add the Notifications too.

**Comment by star-buck** [comment]
there are two "settings": "themeing" settings and "quick" settings like volume, network etc.

in budgie raven sidebar, they make access to quickly change the look of your desktop easy:
![budgie-remix-16 04-raven-sidebar-2](https://cloud.githubusercontent.com/assets/840070/16873587/9065184e-4a94-11e6-84a3-665d9371587d.jpg)

in windows 10 action center you have tiles like phone for quick settings, and notification messenges at top.
![windows_10_action_centre](https://cloud.githubusercontent.com/assets/840070/16873697/23d55544-4a95-11e6-8318-4d15ceca660b.png)

I suggest:
- have notifications at top like win10
- have middle center for themeing like raven bar
- have bottom for quicksettings like win10 (tiles)

**Comment by star-buck** [comment]
as for how to invoke the sidebar:
make it register as an icon in systray or simply make it a widget, so like "notifications" or "volume" widget, it can be placed simply into the panel before or after systray.

Btw. How about calling it "quickpanel"?

**Comment by azubieta** [comment]
All functionalities were implemented in the development branch, please test it. I will be polishing the UI tomorrow.
![screenshot_20160920_161954](https://cloud.githubusercontent.com/assets/1138094/18687561/a458b6f0-7f4e-11e6-8ea0-f92c8263810c.png)

**Comment by UriHerrera** [comment]
Yep. Tested and working.

![](http://i.imgur.com/E14iOld.png)

# 

I don't have icons in the buttons because they're missing from the icon theme.

**Comment by UriHerrera** [comment]
After the commits I made it looks like this:

![](http://i.imgur.com/clL6QJb.png)

# 

Notice that the sidepanel doesn't cover the Plasma panel and on my 21:9 (and also on 16:9 resolutions) the sidepanel isn't too wide anymore. I also added more spacing between the elements in the appearance area. I also changed the size of the titles.

**Comment by UriHerrera** [comment]
I discovered that depending on the theme the borders of the widgets are wider or thinner. In Breeze the values of y: 1 and - 15 below set the sidepanel just above the default panel size of 34 pixels.
![](http://i.imgur.com/uhlxHb9.png)

# 

If the theme used is based on Breeze these values will set the sidepanel "correctly" so to speak in the sense that it puts the sidepanel at the edge of the top part of the screen and above the Plasma panel. However for non-Breeze themes these will look different but not by a whole lot either. 

That doesn't mean _at all_ that if a theme is not based on Breeze it's **wrong or incorrect**, I just want to make that clear.

But I'm taking into consideration the fact that most distributions use Breeze by default or a theme based on it.

I'll illustrate that with this image: 
![](http://i.imgur.com/bndT2QF.png)

The gaps between the shadow (a remnant of the cache) and the solid background of the theme is what I mean.

Clearly, after clearing the Plasma cache it looks like this:
![](http://i.imgur.com/4S4bcJx.png)

Which is because with this theme (Chromeo) in order to make the Chrome OS effect of the taskbar the assets **have to be different from those in Breeze.**

# 

Anyways, the widget is working nicely and I changed the values to position it better when used with Breeze or a Breeze-based theme.

**Comment by azubieta** [comment]
This is how it looks on my screen, it's a little thin don't you think ?
![screenshot_20160922_195010](https://cloud.githubusercontent.com/assets/1138094/18769749/ea5ab17a-80fd-11e6-8409-84932349c643.png)

**Comment by UriHerrera** [comment]
It's somewhere between 6 and 5. With 3.8 definitely it's too wide.

Could be possible to make it resize according to the number of pixels wide so it maintains a ratio?. Well I mean that's kind of what it does, but like for example say, if it's less than 1400 make it this size or if it's over 2560 make it this size.

**Comment by azubieta** [comment]
The idea is to keep the ratio, just measure it when you think it looks good in the different screen ratios, 4:3,16:9 and others, not quite sure of which ones are. The we make the proportions.

**Comment by azubieta** [comment]
The idea is to keep the ratio, just measure it when you think it looks good in the different screen ratios, 4:3,16:9 and others, not quite sure of which ones are. The we make the proportions.

**Comment by azubieta** [comment]
The idea is to keep the ratio, just measure it when you think it looks good in the different screen ratios, 4:3,16:9 and others, not quite sure of which ones are. The we make the proportions.

**Comment by azubieta** [comment]
I made the panel size proportional to the screen height instead of the width. Please test  it.

**Comment by star-buck** [comment]
how about also adding a volume section there that is folded to only show main volume, but can be extended (via small triangle) to show functionality like quickly switch output sources to be lineout, hdmi, headphones, etc?

**Comment by azubieta** [comment]
Sounds good @UriHerrera were should we put those? Also I was thinking in adding some keyboard shortcuts to ease the navigation.

**Comment by UriHerrera** [comment]
I'd say those can be added as a dropdown too above the appearance area. Basically instead of "appearance" it'd be "select audio devices" and the dropdown would show the available outputs.

# 

For the shortcut, is super+q used? it's easy to reach both keys with one hand.

**Comment by star-buck** [comment]
the main audio volume should be visible at all times.
then if the triangle is clicked it should reveal the output sources, which could be shown as dropdowns.

**Comment by UriHerrera** [comment]
The default audio device is displayed in the dropdown with other outputs available when expanded. I also added the volume slider and the marker to indicate it's volume percentage.

![](http://i.imgur.com/ojKQNsw.png)

**Comment by star-buck** [comment]
I dont see how it is expanded?
Also the main volume should be on top and not below. Please google for
veromix to get an idea how it was done.

**Comment by UriHerrera** [comment]
The rectangles with the downward triangle are called dropdowns (or drop down menus). It'd show the other outputs available as a list.

![](http://i.imgur.com/kqRkNSE.png)

It's not the same as the "show extra settings" element which  is a checkbox. They're used for different contexts in an interface.

The placement is by logic. It's common order to first select something and then adjust it's setting(s). Not the other way around, adjusting the settings for an element that hasn't been selected.

# 

This is veromix:
![](https://padoca.files.wordpress.com/2011/03/veromix2.png?w=537&h=386)

Veromix however is a volume **mixer**, which is different than adding only a volume section (to change the master output).

Did you mean to add a mixer instead? @star-buck .

**Comment by star-buck** [comment]
i dont mean a mixer, i mean the main volume, which has a triangle next to it, so when you would search further, you see that if its clicked it reveals the dropdown where you can route it to a different source (headphones, speakers, etc.).

So the volume if the traingle is clicked IS above the dropdown, if in the state as above (hidden), then its just the master volume.
We dont need the application volumes each, so again, only the master volume would be visible and could be routed via dropdown (and to make the dropdown hidden default, we would use a triangle like in veromix).

**Comment by azubieta** [comment]
It's something like this ?
![1](https://cloud.githubusercontent.com/assets/1138094/19018087/ecab32a2-8822-11e6-8c9c-f878a81c1305.png)

**Comment by star-buck** [comment]
I suggest:
- remove text Select playback device
- move Volume slider to where the Select playback device text was

Then if you click triangle, you reveal the routing.

**Comment by azubieta** [comment]
Done! It's in the development branch.

**Comment by star-buck** [comment]
Any screenshot?

**Comment by azubieta** [comment]
![1](https://cloud.githubusercontent.com/assets/1138094/19022702/4f4abe1c-88ac-11e6-8cf4-611c55ee8cad.png)

**Comment by star-buck** [comment]
Is "Built in audio analog stereo" a dropdown (like default look and feel
below)?

Also there is missing a seperation of some sortsbetween audio and select
appearance.

**Comment by azubieta** [comment]
The Look and Fell is a combobox, this is a little different.
Instead of showing a popup with the list of entries when you click the
arrow the whole item move ups showing the entries in a list bellow.

**Comment by star-buck** [comment]
@azubieta : 
please always merge things with master, were only building packages from master.
Also for Blue Systems, I advise people to not have any more than 2 branches, master and dev, and always merge with master (locally you can have as many as you want, but lets avoid that on github, its becoming a mess quickly).

**Comment by azubieta** [comment]
![1](https://cloud.githubusercontent.com/assets/1138094/19040062/7f7ece44-8950-11e6-95e0-0b405688216e.png)
@star-buck roger! Now on I'll keep things in github allays in the master branch. I also fix the panel bottom margin.

**Comment by star-buck** [comment]
here is a similar panel with audio options from solus (budgie desktop):
https://www.youtube.com/watch?v=c0UWhMuXPgk&feature=youtu.be&t=521

**Comment by star-buck** [comment]
i will try the version once compiled, but it looks like how its done is not enough, there is the layer missing where you can assign audio in and out the default channels?

**Comment by star-buck** [comment]
confirmed missing :(

![screenshot_20161003_180719](https://cloud.githubusercontent.com/assets/840070/19044701/b440fbc6-8995-11e6-9993-baa4a30b9600.png)
![screenshot_20161003_180946](https://cloud.githubusercontent.com/assets/840070/19044702/b4451abc-8995-11e6-9036-8fbc858d0cd5.png)

**Comment by star-buck** [comment]
the above is what i get default - its not even offering the non-hdmi channel.
then its still kinda useless if i want to switch ports, that is speakers, headphone etc. since those are not shown as in the real configuration window (this is the whole point: make audio routing dead simple without need for this mess of a config window popup).

**Comment by UriHerrera** [comment]
So this is the structure we're looking for:

volume slider (at the top); expandable/collapsable (_once it's expanded it displays the devices_)
---- Outputs (all of them, not just the selected as default device); checkbox to turn on or off.
-------- Output_device_#1 (default device)
------------- Port_1
------------- Port_2
------------- Etc...
-------- Output_device_#2
-------- Output_device_#3
-------- Etc...
----Inputs (all of them, not just the selected as default device); checkbox to turn on or off.
-------- Input_device_#1 (default device)
-------- Input_device_#2
-------- Input_device_#3
-------- Etc...

So what we're missing from the widget right now is:
- List Input devices. (Inputs don't have Ports or at least there's none in my PC).
- List Ports in a combobox (like the Look n'
  Feel menu) for each Output.
- Turn devices on or off. Since Plasma doesn't use switches anywhere use a checkbox. Though it seems to me that it's more of "mute all" feature rather than on or off.

# 

For me it shows all enabled outputs. I had HDMI disabled and it wasn't listed in the panel, I re enabled it and it was listed in the panel.

**Comment by azubieta** [comment]
@UriHerrera What if instead of a combox for picking the device output we use a radio box. How many ports can have an audio device? guess that the top should be seven or eight.

**Comment by UriHerrera** [comment]
> What if instead of a combox for picking the device output we use a radio box. 

For selecting outputs yes, for selecting the ports of those outputs a dropdown.

> How many ports can have an audio device? guess that the top should be seven or eight.

Analog Stereo Outputs have 2 ports (line in and headphones out). And I can only assume the others like 2.1 have 2 or 3,  5.1 have 5 or 6 and that 7.1 has 7 or 8 (because I don't have any way to realistically be sure of that, I have a 2.0 sound system though my PC supports 7.1 and optical).

**Comment by azubieta** [comment]
I'm spawning a new issue for the audio controls #7, this is getting too long.
