### ISSUE TITLE
Main Window

### ISSUE THREAD

**Issue by azubieta** [plasma-extensions/plasma-widget-quick-controls#2]
Proposed responsibilities:
- Controls the overall behavior of the sidebar-panel and
- contains the individual components.

behavior:
- in which conditions it would be shown or hidden?
- how the user interacts with it ?

architecture:
Are we going to allow for the development of custom components to be embedded on the  sidebar-panel?, I would prefer in order to keep it simple and to achieve a functional prototype earlier to not make it modular at the first but later we can make our own plugin system.

**Comment by UriHerrera** [comment]
> in which conditions it would be shown or hidden?

Through a keyboard shortcut if `Super+P` is not used system wide that can be it.

> Are we going to allow for the development of custom components to be embedded on the sidebar-panel? I would prefer in order to keep it simple and to achieve a functional prototype earlier to not make it modular at the first but later we can make our own plugin system.

I agree too.

**Comment by star-buck** [comment]
i agree to have fixed things in there (see my other comment in issue #1 for info about what to place and how to invoke).
