### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by UriHerrera** [plasma-extensions/plasma-widget-quick-controls#3]
Wireframe to specify the workflow of the quick-panel.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/Lz4oYDz.png)

# 

cc @azubieta @star-buck 

I've made the changes to the workflow as suggested in #1

**Comment by azubieta** [comment]
I'll take the parts corresponding to the notifications to make the notifications panel.

**Comment by azubieta** [comment]
The workflow will deffer in something after moving the notificantions away ?

**Comment by UriHerrera** [comment]
Definitely since the notifications were a big chunk of the main interface. Even if the appearance controls are moved upwards and default to their expanded state there's going to be a lot of space below or in between that and the network switches.

**Comment by star-buck** [comment]
We could expand by adding some more controls, so one could easily change
the basic look with most things in one click reach.

**Comment by azubieta** [comment]
Any update ?

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/JWV8FDA.png)

# 

Since the notifications will no longer be there. What I did was to move the wireless and bluetooth areas and have them show by default. Removed the checkboxes and instead have the toggles turn them on or off. Also added a devices area below them.

**Comment by azubieta** [comment]
Are we going to show only the wireless connections or all network connection ?

**Comment by UriHerrera** [comment]
All of course, wired and wireless.

**Comment by azubieta** [comment]
How the widget will be shown in the panel? Are we going to replace the networkmanager and bluetooth aplets ?

**Comment by UriHerrera** [comment]
Yeah it should replace both. I'll make an icon for it.

**Comment by azubieta** [comment]
Ok,  the theme switches are done.

Now it is only missing the Bluetooth and the "Light-Dark theme Switch". I'm waiting for a USB Bluetooth dongle to arrive in order to test it.
About the "Light-Dark theme Switch" how it should behave when the  theme doesn't provide a dark version ?

**Comment by UriHerrera** [comment]
> About the "Light-Dark theme Switch" how it should behave when the theme doesn't provide a dark version ?

It should change to Breeze Dark. Because just as you say we can't be certain that other themes include a dark version.
