### ISSUE TITLE
plasma-widget-quick-controls does not build

### ISSUE THREAD

**Issue by shadeslayer** [plasma-extensions/plasma-widget-quick-controls#4]
Please see http://dci.pangea.pub/view/Failing/job/stable_stable_ds9-debian-packaging_plasma-widget-quick-controls_bin_amd64/2/console

**Comment by azubieta** [comment]
@shadeslayer this is not even in testing stage. I would  not recomend to sping packages from it yet.

**Comment by shadeslayer** [comment]
I was asked to provide packages, hence the issue :)

**Comment by azubieta** [comment]
Closing this issue until, the package gets more mature.
