### ISSUE TITLE
Audio Controls

### ISSUE THREAD

**Issue by azubieta** [plasma-extensions/plasma-widget-quick-controls#7]
Volume slider (at the top); expandable/collapsable (once it's expanded it displays the devices)
---- Outputs (all of them, not just the selected as default device); checkbox to turn on or off.
-------- Output_device_#1 (default device)
------------- Port_1
------------- Port_2
------------- Etc...
-------- Output_device_#2
-------- Output_device_#3
-------- Etc...
----Inputs (all of them, not just the selected as default device); checkbox to turn on or off.
-------- Input_device_#1 (default device)
-------- Input_device_#2
-------- Input_device_#3
-------- Etc...

So what we're missing from the widget right now is:

```
List Input devices. (Inputs don't have Ports or at least there's none in my PC).
List Ports in a combobox (like the Look n' Feel menu) for each Output.
Turn devices on or off. Since Plasma doesn't use switches anywhere use a checkbox. Though it seems to me that it's more of "mute all" feature rather than on or off.
```

@UriHerrera  would you please draft a simple mockup of how the panel should look like.

**Comment by UriHerrera** [comment]
On it.

**Comment by UriHerrera** [comment]
Here:
- [x] List Input devices.
- [x] List Ports in a combobox
- [x] Turn devices on or off.

![](http://i.imgur.com/KmTpsSe.png)

# 
- Currently active output and input is selected with radio buttons.
- HDMI doesn't provide ports that's why it doesn't have a combobox.

**Comment by star-buck** [comment]
Good mockup, how about combining outputs and inputs as TABS, placing the
TABS above the main volume slider, so when output tab is active, then the
slider below is output volume and when expanding the triangle, it shows
available devices and ports. (Same for input tab).

Also lets remove checkboxes, selecting default via radiobutton seems
sufficient.

**Comment by azubieta** [comment]
Here are some screenshots, the code is in the master branch. Please notice that the "default device" picking is only available with the latest version of plasma-pa. 
![1](https://cloud.githubusercontent.com/assets/1138094/19161190/cb654244-8bc0-11e6-9c16-66f8ddbcbc10.png)
![2](https://cloud.githubusercontent.com/assets/1138094/19161174/bb6c0878-8bc0-11e6-8dc9-0a515236dcf9.png)

**Comment by star-buck** [comment]
Can we condense it some more?
Like combine all dropdown entries from all devices into one dropdown, then
the device to which channel is chosen becomes auto-default (hence
quickcontrol panel)?

If you need more finegrained, you always have the settings option....

**Comment by azubieta** [comment]
You mean something like the previous design but including the input devices in the list and without the tabs?
The devises could be split into sections.

**Comment by star-buck** [comment]
"combine all dropdown entries from the output devices into one dropdown",
that is the hdmi entry + all other output entries into 1 dropdown, not 2.

**Comment by UriHerrera** [comment]
Like this?:

![](http://i.imgur.com/FETQyJm.png)

**Comment by azubieta** [comment]
Are we going to provide a way to change input volume ?
Because as I see it right now it's only possible to change the output volume.

**Comment by UriHerrera** [comment]
I think the first option would be for the slider to control both, if that's possible. The second is that the slider only controls the output and the input volume is changed by going to the actual volume preferences (like Windows does).

**Comment by azubieta** [comment]
Opinions... 
![1](https://cloud.githubusercontent.com/assets/1138094/19288493/4497e330-8fd4-11e6-948f-cf32f76d09aa.png)

**Comment by star-buck** [comment]
okay, lets leave it like that.
Thinking about it, I would also love to see an "extended volume mixer", so lets do that next, ill open a new ticket.

**Comment by azubieta** [comment]
Ok, Some transitions were set to the arrow and to the audio details panel.
Everything was uploaded to the master branch.
